import { ColorModeScript, Container, Divider } from "@yamada-ui/react";
import type { Metadata } from "next";
import { BIZ_UDGothic } from "next/font/google";
import { Header } from "./_layout/header";
import { Providers } from "./_layout/providers";

const font = BIZ_UDGothic({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Form Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <ColorModeScript />
      </head>
      <body className={font.className}>
        <Providers>
          <Header />
          <Divider />
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
